name: mocktailx
description: A set of utility functions over mocktail library created to increase productivity over daily mocking/testing.
homepage: https://github.com/shinayser/mocktailx
version: 0.0.6

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  mocktail: ^1.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.17.5
